//
//  CropModel.swift
//  secondMojong
//
//  Created by Hazzy on 11/27/23.
//

import Foundation

class CropList: ObservableObject {
    @Published var crops: [Crop] = []
    @Published var currentSelectedCrop: Crop
    
    init() {
        currentSelectedCrop = Crop(
            name: "",
            schedule: [
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: [])
            ],
            problem: [
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: []),
                CropMonth(first: [], middle: [], last: [])
            ])
    }
}

struct Crop {
    var name: String
    var isSelected: Bool = false
    var schedule: [CropMonth]
    var problem: [CropMonth]
}

struct CropMonth {
    var first: [Task]
    var middle: [Task]
    var last: [Task]
}

struct Task {
    var title: String
    var detail: String?
}

var cherryTomato: Crop = Crop(
    name: "방울토마토",
    schedule: [
        CropMonth(first: [Task(title: "이식")],
                  middle: [Task(title: "이식")],
                  last: [Task(title: "포트 넓히기"), Task(title: "정식")]
                 ),
        CropMonth(first: [Task(title: "포트 넓히기"), Task(title: "정식")],
                  middle: [Task(title: "포트 넓히기"), Task(title: "정식")],
                  last: [Task(title: "정식"), Task(title: "지주 세우기")]
                 ),
        CropMonth(first: [Task(title: "지주 세우기"), Task(title: "1회 웃거름")],
                  middle: [Task(title: "지주 세우기"), Task(title: "1회 웃거름")],
                  last: [Task(title: "지주 세우기"), Task(title: "1회 웃거름")]),
        CropMonth(first: [Task(title: "2회 웃거름")],
                  middle: [Task(title: "수확"), Task(title: "2회 웃거름")],
                  last: [Task(title: "수확"), Task(title: "2회 웃거름")]),
        CropMonth(first: [Task(title: "수확"), Task(title: "3회 웃거름")],
                  middle: [Task(title: "수확"), Task(title: "3회 웃거름")],
                  last: [Task(title: "수확"), Task(title: "3회 웃거름")]),
        CropMonth(first: [Task(title: "수확")],
                  middle: [],
                  last: []),
        CropMonth(first: [], middle: [], last: []),
        CropMonth(first: [], middle: [], last: []),
        CropMonth(first: [], middle: [], last: []),
        CropMonth(first: [], middle: [], last: []),
        CropMonth(first: [],
                  middle: [],
                  last: [Task(title: "하우스 설치"), Task(title: "종자소독, 파종")]),
        CropMonth(first: [Task(title: "하우스 설치"), Task(title: "종자소독, 파종"), Task(title: "상토 소독")],
                  middle: [Task(title: "하우스 설치"), Task(title: "종자소독, 파종"), Task(title: "상토 소독")],
                  last: [Task(title: "종자소독, 파종"), Task(title: "상토 소독")])
    ],
    problem: [
        CropMonth(first: [Task(title: "폭설, 혹한, 동파 주의", detail: "폭설, 강풍에 대비해 하우스 시설 보강하고 눈이 내리는 즉시 응급 복구하세요."), Task(title: "시설내 저온, 동해, 과습 주의"), Task(title: "육묘불량, 초기 생식불량, 과실 비대불량 주의")],
                  middle: [Task(title: "폭설, 혹한, 동파 주의", detail: "폭설, 강풍에 대비해 하우스 시설 보강하고 눈이 내리는 즉시 응급 복구하세요."), Task(title: "시설내 저온, 동해, 과습 주의"), Task(title: "육묘불량, 초기 생식불량, 과실 비대불량 주의")],
                  last: [Task(title: "폭설, 혹한, 동파 주의", detail: "폭설, 강풍에 대비해 하우스 시설 보강하고 눈이 내리는 즉시 응급 복구하세요."), Task(title: "시설내 저온, 동해, 과습 주의"), Task(title: "육묘불량, 초기 생식불량, 과실 비대불량 주의")]
                 ),
        CropMonth(first: [Task(title: "폭설, 혹한, 동파 주의", detail: "폭설, 강풍에 대비해 하우스 시설 보강하고 눈이 내리는 즉시 응급 복구하세요."), Task(title: "시설내 저온, 동해, 과습 주의"), Task(title: "육묘불량, 초기 생식불량, 과실 비대불량 주의")],
                  middle: [Task(title: "폭설, 혹한, 동파 주의", detail: "폭설, 강풍에 대비해 하우스 시설 보강하고 눈이 내리는 즉시 응급 복구하세요."), Task(title: "시설내 저온, 동해, 과습 주의"), Task(title: "육묘불량, 초기 생식불량, 과실 비대불량 주의")],
                  last: [Task(title: "폭설, 혹한, 동파 주의", detail: "폭설, 강풍에 대비해 하우스 시설 보강하고 눈이 내리는 즉시 응급 복구하세요."), Task(title: "시설내 저온, 동해, 과습 주의"), Task(title: "육묘불량, 초기 생식불량, 과실 비대불량 주의")]
                 ),
        CropMonth(first: [Task(title: "시설 내 3, 4월의 냉해 주의"), Task(title: "생리장해 다발, 낙화, 낙과, 열과, 공동과, 기형과 주의", detail: "열과는 토양이 건조하거나 습한 정도의 변화가 심할 경우 생깁니다. 적절하게 수분을 관리하고, 야간에는 하우스 내의 과습을 억제하기 위해 송풍에 신경씁니다.")],
                  middle: [Task(title: "시설 내 3, 4월의 냉해 주의"), Task(title: "생리장해 다발, 낙화, 낙과, 열과, 공동과, 기형과 주의", detail: "열과는 토양이 건조하거나 습한 정도의 변화가 심할 경우 생깁니다. 적절하게 수분을 관리하고, 야간에는 하우스 내의 과습을 억제하기 위해 송풍에 신경씁니다.")],
                  last: [Task(title: "시설 내 3, 4월의 냉해 주의"), Task(title: "생리장해 다발, 낙화, 낙과, 열과, 공동과, 기형과 주의", detail: "열과는 토양이 건조하거나 습한 정도의 변화가 심할 경우 생깁니다. 적절하게 수분을 관리하고, 야간에는 하우스 내의 과습을 억제하기 위해 송풍에 신경씁니다.")]),
        CropMonth(first: [Task(title: "시설 내 3, 4월의 냉해 주의"), Task(title: "생리장해 다발, 낙화, 낙과, 열과, 공동과, 기형과 주의", detail: "열과는 토양이 건조하거나 습한 정도의 변화가 심할 경우 생깁니다. 적절하게 수분을 관리하고, 야간에는 하우스 내의 과습을 억제하기 위해 송풍에 신경씁니다.")],
                  middle: [Task(title: "시설 내 3, 4월의 냉해 주의"), Task(title: "생리장해 다발, 낙화, 낙과, 열과, 공동과, 기형과 주의", detail: "열과는 토양이 건조하거나 습한 정도의 변화가 심할 경우 생깁니다. 적절하게 수분을 관리하고, 야간에는 하우스 내의 과습을 억제하기 위해 송풍에 신경씁니다.")],
                  last: [Task(title: "시설 내 3, 4월의 냉해 주의"), Task(title: "생리장해 다발, 낙화, 낙과, 열과, 공동과, 기형과 주의", detail: "열과는 토양이 건조하거나 습한 정도의 변화가 심할 경우 생깁니다. 적절하게 수분을 관리하고, 야간에는 하우스 내의 과습을 억제하기 위해 송풍에 신경씁니다.")]),
        CropMonth(first: [Task(title: "건조 시설 내 5, 6월의 고온, 일소, 건조 주의"), Task(title: "생리장해 다발, 낙화, 낙과, 열과, 공동과, 기형과 주의", detail: "열과는 토양이 건조하거나 습한 정도의 변화가 심할 경우 생깁니다. 적절하게 수분을 관리하고, 야간에는 하우스 내의 과습을 억제하기 위해 송풍에 신경씁니다.")],
                  middle: [Task(title: "건조 시설 내 5, 6월의 고온, 일소, 건조 주의"), Task(title: "생리장해 다발, 낙화, 낙과, 열과, 공동과, 기형과 주의", detail: "열과는 토양이 건조하거나 습한 정도의 변화가 심할 경우 생깁니다. 적절하게 수분을 관리하고, 야간에는 하우스 내의 과습을 억제하기 위해 송풍에 신경씁니다.")],
                  last: [Task(title: "건조 시설 내 5, 6월의 고온, 일소, 건조 주의"), Task(title: "생리장해 다발, 낙화, 낙과, 열과, 공동과, 기형과 주의", detail: "열과는 토양이 건조하거나 습한 정도의 변화가 심할 경우 생깁니다. 적절하게 수분을 관리하고, 야간에는 하우스 내의 과습을 억제하기 위해 송풍에 신경씁니다.")]),
        CropMonth(first: [Task(title: "건조 시설 내 5, 6월의 고온, 일소, 건조 주의"), Task(title: "생리장해 다발, 낙화, 낙과, 열과, 공동과, 기형과 주의", detail: "열과는 토양이 건조하거나 습한 정도의 변화가 심할 경우 생깁니다. 적절하게 수분을 관리하고, 야간에는 하우스 내의 과습을 억제하기 위해 송풍에 신경씁니다.")],
                  middle: [Task(title: "건조 시설 내 5, 6월의 고온, 일소, 건조 주의"), Task(title: "생리장해 다발, 낙화, 낙과, 열과, 공동과, 기형과 주의", detail: "열과는 토양이 건조하거나 습한 정도의 변화가 심할 경우 생깁니다. 적절하게 수분을 관리하고, 야간에는 하우스 내의 과습을 억제하기 위해 송풍에 신경씁니다.")],
                  last: []),
        CropMonth(first: [], middle: [], last: []),
        CropMonth(first: [], middle: [], last: []),
        CropMonth(first: [], middle: [], last: []),
        CropMonth(first: [], middle: [], last: []),
        CropMonth(first: [],
                  middle: [Task(title: "폭설, 혹한 동파 주의", detail: "폭설, 강풍에 대비해 하우스 시설 보강하고 눈이 내리는 즉시 응급 복구하세요."), Task(title: "시설 내 저온, 동해, 과습 주의"), Task(title: "육묘불량, 초기 생식불량, 과실 비대불량 주의")],
                  last: [Task(title: "폭설, 혹한 동파 주의", detail: "폭설, 강풍에 대비해 하우스 시설 보강하고 눈이 내리는 즉시 응급 복구하세요."), Task(title: "시설 내 저온, 동해, 과습 주의"), Task(title: "육묘불량, 초기 생식불량, 과실 비대불량 주의")]),
        CropMonth(first: [Task(title: "폭설, 혹한 동파 주의", detail: "폭설, 강풍에 대비해 하우스 시설 보강하고 눈이 내리는 즉시 응급 복구하세요."), Task(title: "시설 내 저온, 동해, 과습 주의"), Task(title: "육묘불량, 초기 생식불량, 과실 비대불량 주의")],
                  middle: [Task(title: "폭설, 혹한 동파 주의", detail: "폭설, 강풍에 대비해 하우스 시설 보강하고 눈이 내리는 즉시 응급 복구하세요."), Task(title: "시설 내 저온, 동해, 과습 주의"), Task(title: "육묘불량, 초기 생식불량, 과실 비대불량 주의")],
                  last: [Task(title: "폭설, 혹한 동파 주의", detail: "폭설, 강풍에 대비해 하우스 시설 보강하고 눈이 내리는 즉시 응급 복구하세요."), Task(title: "시설 내 저온, 동해, 과습 주의"), Task(title: "육묘불량, 초기 생식불량, 과실 비대불량 주의")])
    ]
)

var koreanMelon: Crop = Crop(
    name: "참외",
    schedule: [CropMonth(first: [Task(title: "파종, 육묘 정식")],
                         middle: [Task(title: "파종, 육묘 정식")],
                         last: [Task(title: "파종, 육묘 정식")]),
               CropMonth(first: [Task(title: "정식")],
                         middle: [Task(title: "정식")],
                         last: [Task(title: "유인, 정지, 적심")]),
               CropMonth(first: [Task(title: "유인, 정지, 적심")],
                         middle: [Task(title: "유인, 정지, 적심"), Task(title: "웃거름")],
                         last: [Task(title: "유인, 정지, 적심"), Task(title: "웃거름")]),
               CropMonth(first: [Task(title: "유인, 정지, 적심")],
                         middle: [Task(title: "유인, 정지, 적심"), Task(title: "웃거름")],
                         last: [Task(title: "유인, 정지, 적심"), Task(title: "웃거름")]),
               CropMonth(first: [Task(title: "수확 작업")],
                         middle: [Task(title: "수확 작업"), Task(title: "웃거름")],
                         last: [Task(title: "수확 작업"), Task(title: "웃거름")]),
               CropMonth(first: [Task(title: "수확 작업"), Task(title: "웃거름")],
                         middle: [Task(title: "수확 작업"), Task(title: "웃거름")],
                         last: [Task(title: "수확 작업"), Task(title: "웃거름")]),
               CropMonth(first: [], middle: [], last: []),
               CropMonth(first: [], middle: [], last: []),
               CropMonth(first: [], middle: [], last: []),
               CropMonth(first: [], middle: [], last: []),
               CropMonth(first: [], middle: [], last: []),
               CropMonth(first: [Task(title: "온상 설치")],
                         middle: [Task(title: "온상 설치")],
                         last: [Task(title: "온상 설치")])],
    problem: [CropMonth(first: [Task(title: "혹한 및 저온 주의", detail: "초기생육불량 및 정식지연 주의")],
                        middle: [Task(title: "혹한 및 저온 주의", detail: "낙과, 과실비대불량 기형과 주의")],
                        last: [Task(title: "일조부족, 저온, 가뭄 주의", detail: "낙과, 과실비대불량 기형과 주의")]),
              CropMonth(first: [Task(title: "일조부족, 저온, 가뭄 주의", detail: "낙과, 과실비대불량 기형과 주의")],
                        middle: [Task(title: "일조부족, 저온, 가뭄 주의", detail: "낙과, 과실비대불량 기형과 주의")],
                        last: [Task(title: "일조부족, 저온, 가뭄 주의", detail: "낙과, 과실비대불량 기형과 주의")]),
              CropMonth(first: [Task(title: "일조부족, 저온, 가뭄 주의", detail: "낙과, 과실비대불량 기형과 주의")],
                        middle: [Task(title: "일조부족, 저온, 가뭄 주의", detail: "발효과 생리장해 다발. 발효과 방지를 위해 접목 재배 시 질소질 비료를 과다 시비하지 마세요. 적온을 유지하고 후기에 수분공급을 억제하는 등 적정하게 환경을 관리하세요. 6~8과 정도로 적정 착과하고 적절하게 적심하세요.")],
                        last: [Task(title: "일조부족, 저온, 가뭄 주의", detail: "발효과 생리장해 다발. 발효과 방지를 위해 접목 재배 시 질소질 비료를 과다 시비하지 마세요. 적온을 유지하고 후기에 수분공급을 억제하는 등 적정하게 환경을 관리하세요. 6~8과 정도로 적정 착과하고 적절하게 적심하세요.")]),
              CropMonth(first: [Task(title: "일조부족, 저온, 가뭄 주의", detail: "발효과 생리장해 다발. 발효과 방지를 위해 접목 재배 시 질소질 비료를 과다 시비하지 마세요. 적온을 유지하고 후기에 수분공급을 억제하는 등 적정하게 환경을 관리하세요. 6~8과 정도로 적정 착과하고 적절하게 적심하세요.")],
                        middle: [Task(title: "일조부족, 저온, 가뭄 주의", detail: "발효과 생리장해 다발. 발효과 방지를 위해 접목 재배 시 질소질 비료를 과다 시비하지 마세요. 적온을 유지하고 후기에 수분공급을 억제하는 등 적정하게 환경을 관리하세요. 6~8과 정도로 적정 착과하고 적절하게 적심하세요.")],
                        last: [Task(title: "일조부족, 저온, 가뭄 주의", detail: "발효과 생리장해 다발. 발효과 방지를 위해 접목 재배 시 질소질 비료를 과다 시비하지 마세요. 적온을 유지하고 후기에 수분공급을 억제하는 등 적정하게 환경을 관리하세요. 6~8과 정도로 적정 착과하고 적절하게 적심하세요.")]),
              CropMonth(first: [Task(title: "고온 주의", detail: "생리장해 발생, 병해충 다발생")],
                        middle: [Task(title: "고온 주의", detail: "생리장해 발생, 병해충 다발생")],
                        last: [Task(title: "고온 주의", detail: "생리장해 발생, 병해충 다발생")]),
              CropMonth(first: [Task(title: "고온 주의", detail: "생리장해 발생, 병해충 다발생")],
                        middle: [Task(title: "고온 주의", detail: "생리장해 발생, 병해충 다발생")],
                        last: [Task(title: "고온 주의", detail: "생리장해 발생, 병해충 다발생")]),
              CropMonth(first: [Task(title: "고온 주의", detail: "생리장해 발생, 병해충 다발생")],
                        middle: [],
                        last: []),
              CropMonth(first: [], middle: [], last: []),
              // TODO: 여기 아닐지도...
              CropMonth(first: [], middle: [], last: []),
              CropMonth(first: [], middle: [], last: []),
              CropMonth(first: [],
                        middle: [Task(title: "혹한 및 저온 주의", detail: "초기생육불량 및 정식 지연 주의")],
                        last: [Task(title: "혹한 및 저온 주의", detail: "초기생육불량 및 정식 지연 주의")]),
              CropMonth(first: [Task(title: "혹한 및 저온 주의", detail: "초기생육불량 및 정식 지연 주의")],
                        middle: [Task(title: "혹한 및 저온 주의", detail: "초기생육불량 및 정식 지연 주의")],
                        last: [Task(title: "혹한 및 저온 주의", detail: "초기생육불량 및 정식 지연 주의")])])

var cabbage: Crop = Crop(
    name: "배추",
    schedule: [CropMonth(first: [Task(title: "유묘기: 파종")],
                         middle: [Task(title: "파종")],
                         last: [Task(title: "파종")]),
               CropMonth(first: [Task(title: "파종")],
                         middle: [Task(title: "경업신장기: 정식, 웃거름"), Task(title: "경업신장기: 중경제초, 관배수")],
                         last: [Task(title: "경업신장기: 정식, 웃거름"), Task(title: "경업신장기: 중경제초, 관배수")]),
               CropMonth(first: [Task(title: "경업신장기: 정식, 웃거름"), Task(title: "경업신장기: 중경제초, 관배수")],
                         middle: [Task(title: "경업신장기: 정식, 웃거름"), Task(title: "경업신장기: 중경제초, 관배수")],
                         last: [Task(title: "경업신장기: 정식, 웃거름"), Task(title: "경업신장기: 중경제초, 관배수"), Task(title: "결구기: 수확")]),
               CropMonth(first: [Task(title: "결구기: 정식, 웃거름"), Task(title: "결구기: 중경제초, 관배수"), Task(title: "결구기: 수확")],
                         middle: [Task(title: "결구기: 정식, 웃거름"), Task(title: "결구기: 중경제초, 관배수"), Task(title: "결구기: 수확")],
                         last: [Task(title: "결구기: 수확")]),
               CropMonth(first: [Task(title: "결구기: 수확")],
                         middle: [Task(title: "결구기: 수확")],
                         last: []),
               CropMonth(first: [],
                         middle: [],
                         last: []),
               CropMonth(first: [Task(title: "유묘기: 파종")],
                         middle: [Task(title: "유묘기: 파종")],
                         last: [Task(title: "유묘기: 파종"), Task(title: "경업신장기: 정식, 웃거름"),Task(title: "경업신장기: 중경제초, 관배수")]),
               CropMonth(first: [Task(title: "경업신장기: 정식, 웃거름"),Task(title: "경업신장기: 중경제초, 관배수")],
                         middle: [Task(title: "경업신장기: 정식, 웃거름"),Task(title: "경업신장기: 중경제초, 관배수")],
                         last: [Task(title: "경업신장기: 정식, 웃거름"),Task(title: "경업신장기: 중경제초, 관배수")]),
               CropMonth(first: [Task(title: "경업신장기: 정식, 웃거름"),Task(title: "경업신장기: 중경제초, 관배수")],
                         middle: [Task(title: "결구기: 정식, 웃거름"),Task(title: "결구기: 중경제초, 관배수")],
                         last: [Task(title: "결구기: 정식, 웃거름"),Task(title: "결구기: 중경제초, 관배수"), Task(title: "결구기: 수확")]),
               CropMonth(first: [Task(title: "결구기: 수확"), Task(title: "결구기: 저장")],
                         middle: [Task(title: "결구기: 수확"), Task(title: "결구기: 저장")],
                         last: []),
               CropMonth(first: [],
                         middle: [],
                         last: []),
               CropMonth(first: [],
                         middle: [],
                         last: [])
    ],
    problem: [CropMonth(first: [Task(title: "저온 및 혹한 주의", detail: "발아 불량, 초기생육 불량, 동해에 주의합니다. 저온 추대를 위해 저온감응이 둔한 품종을 재배합니다. 배추 육묘 시 야간에 10℃ 이상 보온합니다.")],
                        middle: [Task(title: "저온 및 혹한 주의", detail: "발아 불량, 초기생육 불량, 동해에 주의합니다. 저온 추대를 위해 저온감응이 둔한 품종을 재배합니다. 배추 육묘 시 야간에 10℃ 이상 보온합니다.")],
                        last: [Task(title: "저온 및 혹한 주의", detail: "발아 불량, 초기생육 불량, 동해에 주의합니다. 저온 추대를 위해 저온감응이 둔한 품종을 재배합니다. 배추 육묘 시 야간에 10℃ 이상 보온합니다.")]),
              CropMonth(first: [Task(title: "저온 및 혹한 주의", detail: "발아 불량, 초기생육 불량, 동해에 주의합니다. 저온 추대를 위해 저온감응이 둔한 품종을 재배합니다. 배추 육묘 시 야간에 10℃ 이상 보온합니다.")],
                        middle: [Task(title: "저온 및 혹한 주의", detail: "발아 불량, 초기생육 불량, 동해에 주의합니다. 저온 추대를 위해 저온감응이 둔한 품종을 재배합니다. 배추 육묘 시 야간에 10℃ 이상 보온합니다.")],
                        last: [Task(title: "저온 및 혹한 주의", detail: "발아 불량, 초기생육 불량, 동해에 주의합니다. 저온 추대를 위해 저온감응이 둔한 품종을 재배합니다. 배추 육묘 시 야간에 10℃ 이상 보온합니다.")]),
              CropMonth(first: [Task(title: "저온 및 혹한 주의", detail: "발아 불량, 초기생육 불량, 동해에 주의합니다. 저온 추대를 위해 저온감응이 둔한 품종을 재배합니다. 배추 육묘 시 야간에 10℃ 이상 보온합니다.")],
                        middle: [Task(title: "적은 비와 가뭄 주의", detail: "습해와 병해충에 주의합니다. 봄가뭄에 대비하기 위해 관수에 신경 쓰고 짚과 비닐을 덮는 등 수분이 날아가지 않도록 주의합니다. 병해충에 적절한 살충제를 살포합니다.")],
                        last: [Task(title: "적은 비와 가뭄 주의", detail: "습해와 병해충에 주의합니다. 봄가뭄에 대비하기 위해 관수에 신경 쓰고 짚과 비닐을 덮는 등 수분이 날아가지 않도록 주의합니다. 병해충에 적절한 살충제를 살포합니다.")]),
              CropMonth(first: [Task(title: "적은 비와 가뭄 주의", detail: "습해와 병해충에 주의합니다. 봄가뭄에 대비하기 위해 관수에 신경 쓰고 짚과 비닐을 덮는 등 수분이 날아가지 않도록 주의합니다. 병해충에 적절한 살충제를 살포합니다.")],
                        middle: [Task(title: "적은 비와 가뭄 주의", detail: "습해와 병해충에 주의합니다. 봄가뭄에 대비하기 위해 관수에 신경 쓰고 짚과 비닐을 덮는 등 수분이 날아가지 않도록 주의합니다. 병해충에 적절한 살충제를 살포합니다.")],
                        last: [Task(title: "적은 비와 가뭄 주의", detail: "습해와 병해충에 주의합니다. 봄가뭄에 대비하기 위해 관수에 신경 쓰고 짚과 비닐을 덮는 등 수분이 날아가지 않도록 주의합니다. 병해충에 적절한 살충제를 살포합니다.")]),
              CropMonth(first: [Task(title: "적은 비와 가뭄 주의", detail: "습해와 병해충에 주의합니다. 봄가뭄에 대비하기 위해 관수에 신경 쓰고 짚과 비닐을 덮는 등 수분이 날아가지 않도록 주의합니다. 병해충에 적절한 살충제를 살포합니다.")],
                        middle: [Task(title: "적은 비와 가뭄 주의", detail: "습해와 병해충에 주의합니다. 봄가뭄에 대비하기 위해 관수에 신경 쓰고 짚과 비닐을 덮는 등 수분이 날아가지 않도록 주의합니다. 병해충에 적절한 살충제를 살포합니다.")],
                        last: [Task(title: "적은 비와 가뭄 주의", detail: "습해와 병해충에 주의합니다. 봄가뭄에 대비하기 위해 관수에 신경 쓰고 짚과 비닐을 덮는 등 수분이 날아가지 않도록 주의합니다. 병해충에 적절한 살충제를 살포합니다.")]),
              CropMonth(first: [],
                        middle: [],
                        last: []),
              CropMonth(first: [],
                        middle: [],
                        last: []),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "가을 가뭄 주의를 위해 이동식 스프링쿨러를 설치해 관수하고 짚을 덮는 등 관리합니다. 망사를 피복하고 병해충에 적절한 살충제를 살포합니다. "), Task(title: "호우로 침관수 유실, 매몰 주의", detail: "배수구를 정비합니다. 조생종과 반결구종의 경우 재파 혹은 보파합니다. 엽면에 시비하고 살균제를 살포합니다. ")],
                        middle: [Task(title: "가뭄 주의", detail: "가을 가뭄 주의를 위해 이동식 스프링쿨러를 설치해 관수하고 짚을 덮는 등 관리합니다. 망사를 피복하고 병해충에 적절한 살충제를 살포합니다. "), Task(title: "호우로 침관수 유실, 매몰 주의", detail: "배수구를 정비합니다. 조생종과 반결구종의 경우 재파 혹은 보파합니다. 엽면에 시비하고 살균제를 살포합니다. ")],
                        last: [Task(title: "가뭄 주의", detail: "가을 가뭄 주의를 위해 이동식 스프링쿨러를 설치해 관수하고 짚을 덮는 등 관리합니다. 망사를 피복하고 병해충에 적절한 살충제를 살포합니다. "), Task(title: "호우로 침관수 유실, 매몰 주의", detail: "배수구를 정비합니다. 조생종과 반결구종의 경우 재파 혹은 보파합니다. 엽면에 시비하고 살균제를 살포합니다. ")]),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "가을 가뭄 주의를 위해 이동식 스프링쿨러를 설치해 관수하고 짚을 덮는 등 관리합니다. 망사를 피복하고 병해충에 적절한 살충제를 살포합니다. "), Task(title: "호우로 침관수 유실, 매몰 주의", detail: "배수구를 정비합니다. 조생종과 반결구종의 경우 재파 혹은 보파합니다. 엽면에 시비하고 살균제를 살포합니다. ")],
                        middle: [Task(title: "가뭄 주의", detail: "가을 가뭄 주의를 위해 이동식 스프링쿨러를 설치해 관수하고 짚을 덮는 등 관리합니다. 망사를 피복하고 병해충에 적절한 살충제를 살포합니다. "), Task(title: "결구불량, 바이러스병 다발 주의")],
                        last: [Task(title: "가뭄 주의", detail: "가을 가뭄 주의를 위해 이동식 스프링쿨러를 설치해 관수하고 짚을 덮는 등 관리합니다. 망사를 피복하고 병해충에 적절한 살충제를 살포합니다. "), Task(title: "결구불량, 바이러스병 다발 주의")]),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "가을 가뭄 주의를 위해 이동식 스프링쿨러를 설치해 관수하고 짚을 덮는 등 관리합니다. 망사를 피복하고 병해충에 적절한 살충제를 살포합니다. "), Task(title: "결구불량, 바이러스병 다발 주의")],
                        middle: [Task(title: "가뭄 주의", detail: "가을 가뭄 주의를 위해 이동식 스프링쿨러를 설치해 관수하고 짚을 덮는 등 관리합니다. 망사를 피복하고 병해충에 적절한 살충제를 살포합니다. "), Task(title: "결구불량, 바이러스병 다발 주의")],
                        last: [Task(title: "가뭄 주의", detail: "가을 가뭄 주의를 위해 이동식 스프링쿨러를 설치해 관수하고 짚을 덮는 등 관리합니다. 망사를 피복하고 병해충에 적절한 살충제를 살포합니다. "), Task(title: "결구불량, 바이러스병 다발 주의")]),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "가을 가뭄 주의를 위해 이동식 스프링쿨러를 설치해 관수하고 짚을 덮는 등 관리합니다. 망사를 피복하고 병해충에 적절한 살충제를 살포합니다. "), Task(title: "결구불량, 바이러스병 다발 주의")],
                        middle: [Task(title: "한파, 동해 주의", detail: "동해 온도는 -3~-4℃ 정도로 유지합니다. 섬피 또는 비닐을 덮어 보온합니다. 적기에 수확하고 임시저장 및 움저장합니다.")],
                        last: []),
              CropMonth(first: [],
                        middle: [],
                        last: [])])

var chiliPepper: Crop = Crop(
    name: "고추",
    schedule: [CropMonth(first: [Task(title: "온상 설치")],
                         middle: [Task(title: "온상 설치")],
                         last: [Task(title: "발아기, 육모기: 온상 설치")]),
               CropMonth(first: [Task(title: "발아기, 육모기: 파종")],
                         middle: [Task(title: "발아기, 육모기: 파종")],
                         last: [Task(title: "발아기, 육모기: 파종")]),
               CropMonth(first: [Task(title: "발아기, 육모기: 파종")],
                         middle: [Task(title: "발아기, 육모기: 파종")],
                         last: [Task(title: "발아기, 육모기: 정식")]),
               CropMonth(first: [Task(title: "정식기: 정식")],
                         middle: [Task(title: "정식기: 정식"), Task(title: "정식기: 지주설치, 유인")],
                         last: [Task(title: "정식기: 지주설치, 유인"), Task(title: "정식기: 1회 웃거름")]),
               CropMonth(first: [Task(title: "개화기: 지주설치, 유인"), Task(title: "개화기: 1회 웃거름")],
                         middle: [Task(title: "개화기: 지주설치, 유인"), Task(title: "개화기: 1회 웃거름")],
                         last: [Task(title: "개화기: 지주설치, 유인"), Task(title: "개화기: 2회 웃거름")]),
               CropMonth(first: [Task(title: "개화기: 2회 웃거름"), Task(title: "개화기: 풋고추 수확")],
                         middle: [Task(title: "개화기: 2회 웃거름"), Task(title: "개화기: 풋고추 수확")],
                         last: [Task(title: "개화기: 2회 웃거름"), Task(title: "개화기: 풋고추 수확"), Task(title: "개화기: 붉은고추 수확")]),
               CropMonth(first: [Task(title: "개화기: 붉은고추 수확")],
                         middle: [Task(title: "개화기: 붉은고추 수확"), Task(title: "개화기: 3회 웃거름")],
                         last: [Task(title: "개화기: 붉은고추 수확"), Task(title: "개화기: 3회 웃거름")]),
               CropMonth(first: [Task(title: "개화기: 붉은고추 수확"), Task(title: "개화기: 3회 웃거름")],
                         middle: [Task(title: "붉은고추 수확")],
                         last: [Task(title: "붉은고추 수확")]),
               CropMonth(first: [Task(title: "붉은고추 수확")],
                         middle: [Task(title: "붉은고추 수확"), Task(title: "생산량 및 수량 감소 시 연장 재배")],
                         last: [Task(title: "생산량 및 수량 감소 시 연장 재배")]),
               CropMonth(first: [Task(title: "생산량 및 수량 감소 시 연장 재배")],
                         middle: [Task(title: "생산량 및 수량 감소 시 연장 재배")],
                         last: [Task(title: "생산량 및 수량 감소 시 연장 재배")]),
               CropMonth(first: [Task(title: "생산량 및 수량 감소 시 연장 재배")],
                         middle: [Task(title: "생산량 및 수량 감소 시 연장 재배")],
                         last: [Task(title: "생산량 및 수량 감소 시 연장 재배")]),
               CropMonth(first: [Task(title: "생산량 및 수량 감소 시 연장 재배")],
                         middle: [],
                         last: []),
    ],
    problem: [CropMonth(first: [],
                        middle: [],
                        last: [Task(title: "혹한 및 저온 주의", detail: "육묘 불량 주의. 모잘록병 방제를 위해 병해 발생 시 정식을 지연합니다. 야간에는 15℃ 이상 보온합니다. ")]),
              CropMonth(first: [Task(title: "혹한 및 저온 주의", detail: "육묘 불량 주의. 모잘록병 방제를 위해 병해 발생 시 정식을 지연합니다. 야간에는 15℃ 이상 보온합니다. ")],
                        middle: [Task(title: "혹한 및 저온 주의", detail: "육묘 불량 주의. 모잘록병 방제를 위해 병해 발생 시 정식을 지연합니다. 야간에는 15℃ 이상 보온합니다. ")],
                        last: [Task(title: "혹한 및 저온 주의", detail: "육묘 불량 주의. 모잘록병 방제를 위해 병해 발생 시 정식을 지연합니다. 야간에는 15℃ 이상 보온합니다. ")]),
              CropMonth(first: [Task(title: "혹한 및 저온 주의", detail: "육묘 불량 주의. 모잘록병 방제를 위해 병해 발생 시 정식을 지연합니다. 야간에는 15℃ 이상 보온합니다. ")],
                        middle: [Task(title: "혹한 및 저온 주의", detail: "육묘 불량 주의. 모잘록병 방제를 위해 병해 발생 시 정식을 지연합니다. 야간에는 15℃ 이상 보온합니다. "), Task(title: "가뭄 주의", detail: "가뭄에 대비하기 위해 관수 후 정식합니다. 비닐을 덮어 재배해도 좋습니다.")],
                        last: [Task(title: "혹한 및 저온 주의", detail: "육묘 불량 주의. 모잘록병 방제를 위해 병해 발생 시 정식을 지연합니다. 야간에는 15℃ 이상 보온합니다. "), Task(title: "가뭄 주의", detail: "가뭄에 대비하기 위해 관수 후 정식합니다. 비닐을 덮어 재배해도 좋습니다.")]),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "가뭄에 대비하기 위해 관수 후 정식합니다. 비닐을 덮어 재배해도 좋습니다.")],
                        middle: [Task(title: "가뭄 주의", detail: "가뭄에 대비하기 위해 관수 후 정식합니다. 비닐을 덮어 재배해도 좋습니다.")],
                        last: [Task(title: "가뭄 주의", detail: "가뭄에 대비하기 위해 관수 후 정식합니다. 비닐을 덮어 재배해도 좋습니다.")]),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "가뭄에 대비하기 위해 관수 후 정식합니다. 비닐을 덮어 재배해도 좋습니다.")],
                        middle: [Task(title: "가뭄 주의", detail: "가뭄에 대비하기 위해 관수 후 정식합니다. 비닐을 덮어 재배해도 좋습니다."), Task(title: "장마 습해 주의", detail: "돌림병, 낙화에 주의합니다. 담배나방에 주의합니다. 7~10일 간격으로 살균제를 살포해 병해충을 종합적으로 방제합니다. 배수구를 정비합니다. 추비 사용을 금지합니다.")],
                        last: [Task(title: "장마 습해 주의", detail: "돌림병, 낙화에 주의합니다. 담배나방에 주의합니다. 7~10일 간격으로 살균제를 살포해 병해충을 종합적으로 방제합니다. 배수구를 정비합니다. 추비 사용을 금지합니다.")]),
              CropMonth(first: [Task(title: "장마 습해 주의", detail: "돌림병, 낙화에 주의합니다. 담배나방에 주의합니다. 7~10일 간격으로 살균제를 살포해 병해충을 종합적으로 방제합니다. 배수구를 정비합니다. 추비 사용을 금지합니다.")],
                        middle: [Task(title: "장마 습해 주의", detail: "돌림병, 낙화에 주의합니다. 담배나방에 주의합니다. 7~10일 간격으로 살균제를 살포해 병해충을 종합적으로 방제합니다. 배수구를 정비합니다. 추비 사용을 금지합니다.")],
                        last: [Task(title: "장마 습해 주의", detail: "돌림병, 낙화에 주의합니다. 담배나방에 주의합니다. 7~10일 간격으로 살균제를 살포해 병해충을 종합적으로 방제합니다. 배수구를 정비합니다. 추비 사용을 금지합니다.")]),
              CropMonth(first: [Task(title: "장마 습해 주의", detail: "돌림병, 낙화에 주의합니다. 담배나방에 주의합니다. 7~10일 간격으로 살균제를 살포해 병해충을 종합적으로 방제합니다. 배수구를 정비합니다. 추비 사용을 금지합니다.")],
                        middle: [Task(title: "가뭄 주의", detail: "관수하고 고랑에 짚을 덮습니다.")],
                        last: [Task(title: "가뭄 주의", detail: "관수하고 고랑에 짚을 덮습니다.")]),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "관수하고 고랑에 짚을 덮습니다.")],
                        middle: [Task(title: "가뭄 주의", detail: "관수하고 고랑에 짚을 덮습니다."), Task(title: "호우, 태풍 주의", detail: "습해, 도복, 낙과, 건조곤란에 주의합니다. 지주를 보완하고 도복주를 세우는 등 관리합니다. 엽면에 시비하고 배수를 철저하게 관리합니다. 수확한 고추는 열풍 건조기를 이용해 건조합니다.")],
                        last: [Task(title: "가뭄 주의", detail: "관수하고 고랑에 짚을 덮습니다."), Task(title: "호우, 태풍 주의", detail: "습해, 도복, 낙과, 건조곤란에 주의합니다. 지주를 보완하고 도복주를 세우는 등 관리합니다. 엽면에 시비하고 배수를 철저하게 관리합니다. 수확한 고추는 열풍 건조기를 이용해 건조합니다.")]),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "관수하고 고랑에 짚을 덮습니다."), Task(title: "호우, 태풍 주의", detail: "습해, 도복, 낙과, 건조곤란에 주의합니다. 지주를 보완하고 도복주를 세우는 등 관리합니다. 엽면에 시비하고 배수를 철저하게 관리합니다. 수확한 고추는 열풍 건조기를 이용해 건조합니다.")],
                        middle: [Task(title: "가뭄 주의", detail: "관수하고 고랑에 짚을 덮습니다."), Task(title: "호우, 태풍 주의", detail: "습해, 도복, 낙과, 건조곤란에 주의합니다. 지주를 보완하고 도복주를 세우는 등 관리합니다. 엽면에 시비하고 배수를 철저하게 관리합니다. 수확한 고추는 열풍 건조기를 이용해 건조합니다.")],
                        last: [Task(title: "가뭄 주의", detail: "관수하고 고랑에 짚을 덮습니다."), Task(title: "호우, 태풍 주의", detail: "습해, 도복, 낙과, 건조곤란에 주의합니다. 지주를 보완하고 도복주를 세우는 등 관리합니다. 엽면에 시비하고 배수를 철저하게 관리합니다. 수확한 고추는 열풍 건조기를 이용해 건조합니다.")]),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "관수하고 고랑에 짚을 덮습니다.")],
                        middle: [Task(title: "가뭄 주의", detail: "관수하고 고랑에 짚을 덮습니다.")],
                        last: [Task(title: "가뭄 주의", detail: "관수하고 고랑에 짚을 덮습니다.")]),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "관수하고 고랑에 짚을 덮습니다."), Task(title: "저온 주의")],
                        middle: [Task(title: "가뭄 주의", detail: "관수하고 고랑에 짚을 덮습니다."), Task(title: "저온 주의")],
                        last: [Task(title: "가뭄 주의", detail: "관수하고 고랑에 짚을 덮습니다."), Task(title: "저온 주의")]),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "관수하고 고랑에 짚을 덮습니다."), Task(title: "저온 주의")],
                        middle: [],
                        last: []),
   ])

var lettuce: Crop = Crop(
    name: "상추",
    schedule: [CropMonth(first: [Task(title: "시설봄재배: 파종"), Task(title: "겨울재배: 수확")],
                         middle: [Task(title: "시설봄재배: 파종"), Task(title: "겨울재배: 수확")],
                         last: [Task(title: "시설봄재배: 파종"), Task(title: "겨울재배: 수확")]),
               CropMonth(first: [Task(title: "시설봄재배: 파종"), Task(title: "겨울재배: 수확"), Task(title: "시설봄재배: 정식")],
                         middle: [Task(title: "겨울재배: 수확"), Task(title: "시설봄재배: 정식")],
                         last: [Task(title: "겨울재배: 수확"), Task(title: "시설봄재배: 정식")]),
               CropMonth(first: [Task(title: "겨울재배: 수확"), Task(title: "시설봄재배: 정식")],
                         middle: [Task(title: "겨울재배: 수확"), Task(title: "시설봄재배: 수확")],
                         last: [Task(title: "겨울재배: 수확"), Task(title: "시설봄재배: 수확")]),
               CropMonth(first: [Task(title: "시설봄재배: 수확")],
                         middle: [Task(title: "시설봄재배: 수확")],
                         last: [Task(title: "시설봄재배: 수확")]),
               CropMonth(first: [Task(title: "시설봄재배: 수확"), Task(title: "여름재배: 파종")],
                         middle: [Task(title: "시설봄재배: 수확"), Task(title: "여름재배: 파종")],
                         last: [Task(title: "시설봄재배: 수확")]),
               CropMonth(first: [Task(title: "여름재배: 정식")],
                         middle: [Task(title: "여름재배: 정식")],
                         last: []),
               CropMonth(first: [Task(title: "여름재배: 수확")],
                         middle: [Task(title: "여름재배: 수확")],
                         last: [Task(title: "여름재배: 수확"), Task(title: "가을재배: 파종")]),
               CropMonth(first: [Task(title: "여름재배: 수확"), Task(title: "가을재배: 파종")],
                         middle: [Task(title: "가을재배: 정식")],
                         last: [Task(title: "가을재배: 정식")]),
               CropMonth(first: [Task(title: "가을재배: 수확")],
                         middle: [Task(title: "가을재배: 수확")],
                         last: [Task(title: "가을재배: 수확")]),
               CropMonth(first: [Task(title: "가을재배: 수확")],
                         middle: [Task(title: "가을재배: 수확"), Task(title: "겨울재배: 파종")],
                         last: [Task(title: "가을재배: 수확"), Task(title: "겨울재배: 파종")]),
               CropMonth(first: [],
                         middle: [],
                         last: [Task(title: "겨울재배: 정식")]),
               CropMonth(first: [Task(title: "겨울재배: 정식")],
                         middle: [],
                         last: []),
    ],
    problem: [CropMonth(first: [Task(title: "혹한기 동해, 생육불량 주의", detail: "보온 덮개 또는 터널을 이용한 보온 수막 재배합니다. 투광성과 보온성이 높은 피복자재를 설치합니다.")],
                        middle: [Task(title: "혹한기 동해, 생육불량 주의", detail: "보온 덮개 또는 터널을 이용한 보온 수막 재배합니다. 투광성과 보온성이 높은 피복자재를 설치합니다.")],
                        last: [Task(title: "혹한기 동해, 생육불량 주의", detail: "보온 덮개 또는 터널을 이용한 보온 수막 재배합니다. 투광성과 보온성이 높은 피복자재를 설치합니다.")]),
              CropMonth(first: [Task(title: "혹한기 동해, 생육불량 주의", detail: "보온 덮개 또는 터널을 이용한 보온 수막 재배합니다. 투광성과 보온성이 높은 피복자재를 설치합니다.")],
                        middle: [Task(title: "혹한기 동해, 생육불량 주의", detail: "보온 덮개 또는 터널을 이용한 보온 수막 재배합니다. 투광성과 보온성이 높은 피복자재를 설치합니다.")],
                        last: [Task(title: "혹한기 동해, 생육불량 주의", detail: "보온 덮개 또는 터널을 이용한 보온 수막 재배합니다. 투광성과 보온성이 높은 피복자재를 설치합니다.")]),
              CropMonth(first: [],
                        middle: [],
                        last: []),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "흑색 PE필름을 멀칭하고 관수합니다.")],
                        middle: [],
                        last: []),
              CropMonth(first: [],
                        middle: [Task(title: "장마, 호우 및 태풍 주의", detail: "배수와 시설 안전관리를 철저히 합니다. 예방적으로 병해충 방제를 실시하고 엽면에 시비합니다."), Task(title: "고온 주의", detail: "35% 이하의 흑색 차광막을 이용합니다. 환기를 철저히 합니다. 예방적으로 병해충을 방제합니다.")],
                        last: [Task(title: "장마, 호우 및 태풍 주의", detail: "배수와 시설 안전관리를 철저히 합니다. 예방적으로 병해충 방제를 실시하고 엽면에 시비합니다."), Task(title: "고온 주의", detail: "35% 이하의 흑색 차광막을 이용합니다. 환기를 철저히 합니다. 예방적으로 병해충을 방제합니다.")]),
              CropMonth(first: [Task(title: "장마, 호우 및 태풍 주의", detail: "배수와 시설 안전관리를 철저히 합니다. 예방적으로 병해충 방제를 실시하고 엽면에 시비합니다."), Task(title: "고온 주의", detail: "35% 이하의 흑색 차광막을 이용합니다. 환기를 철저히 합니다. 예방적으로 병해충을 방제합니다.")],
                        middle: [Task(title: "장마, 호우 및 태풍 주의", detail: "배수와 시설 안전관리를 철저히 합니다. 예방적으로 병해충 방제를 실시하고 엽면에 시비합니다."), Task(title: "고온 주의", detail: "35% 이하의 흑색 차광막을 이용합니다. 환기를 철저히 합니다. 예방적으로 병해충을 방제합니다.")],
                        last: [Task(title: "장마, 호우 및 태풍 주의", detail: "배수와 시설 안전관리를 철저히 합니다. 예방적으로 병해충 방제를 실시하고 엽면에 시비합니다."), Task(title: "고온 주의", detail: "35% 이하의 흑색 차광막을 이용합니다. 환기를 철저히 합니다. 예방적으로 병해충을 방제합니다.")]),
              CropMonth(first: [Task(title: "장마, 호우 및 태풍 주의", detail: "배수와 시설 안전관리를 철저히 합니다. 예방적으로 병해충 방제를 실시하고 엽면에 시비합니다."), Task(title: "고온 주의", detail: "35% 이하의 흑색 차광막을 이용합니다. 환기를 철저히 합니다. 예방적으로 병해충을 방제합니다.")],
                        middle: [Task(title: "장마, 호우 및 태풍 주의", detail: "배수와 시설 안전관리를 철저히 합니다. 예방적으로 병해충 방제를 실시하고 엽면에 시비합니다."), Task(title: "고온 주의", detail: "35% 이하의 흑색 차광막을 이용합니다. 환기를 철저히 합니다. 예방적으로 병해충을 방제합니다.")],
                        last: [Task(title: "장마, 호우 및 태풍 주의", detail: "배수와 시설 안전관리를 철저히 합니다. 예방적으로 병해충 방제를 실시하고 엽면에 시비합니다."), Task(title: "고온 주의", detail: "35% 이하의 흑색 차광막을 이용합니다. 환기를 철저히 합니다. 예방적으로 병해충을 방제합니다.")]),
              CropMonth(first: [Task(title: "장마, 호우 및 태풍 주의", detail: "배수와 시설 안전관리를 철저히 합니다. 예방적으로 병해충 방제를 실시하고 엽면에 시비합니다."), Task(title: "고온 주의", detail: "35% 이하의 흑색 차광막을 이용합니다. 환기를 철저히 합니다. 예방적으로 병해충을 방제합니다.")],
                        middle: [],
                        last: []),
              CropMonth(first: [],
                        middle: [],
                        last: []),
              CropMonth(first: [Task(title: "저온 주의", detail: "생육부진에 주의합니다. 보온덮개 또는 터널을 이용해 보온 수막 재배합니다. 투광성과 보온성이 높은 피복자재를 설치합니다.")],
                        middle: [Task(title: "저온 주의", detail: "생육부진에 주의합니다. 보온덮개 또는 터널을 이용해 보온 수막 재배합니다. 투광성과 보온성이 높은 피복자재를 설치합니다.")],
                        last: [Task(title: "저온 주의", detail: "생육부진에 주의합니다. 보온덮개 또는 터널을 이용해 보온 수막 재배합니다. 투광성과 보온성이 높은 피복자재를 설치합니다.")]),
              CropMonth(first: [Task(title: "저온 주의", detail: "생육부진에 주의합니다. 보온덮개 또는 터널을 이용해 보온 수막 재배합니다. 투광성과 보온성이 높은 피복자재를 설치합니다.")],
                        middle: [Task(title: "저온 주의", detail: "생육부진에 주의합니다. 보온덮개 또는 터널을 이용해 보온 수막 재배합니다. 투광성과 보온성이 높은 피복자재를 설치합니다.")],
                        last: []),
              CropMonth(first: [],
                        middle: [],
                        last: []),
   ])

var leafMustard: Crop = Crop(
    name: "갓",
    schedule: [CropMonth(first: [],
                         middle: [],
                         last: []),
               CropMonth(first: [],
                         middle: [],
                         last: []),
               CropMonth(first: [],
                         middle: [],
                         last: [Task(title: "파종")]),
               CropMonth(first: [Task(title: "파종"),Task(title: "웃거름")],
                         middle: [Task(title: "파종"),Task(title: "웃거름"), Task(title: "제초, 관수 및 배수")],
                         last: [Task(title: "웃거름"), Task(title: "제초, 관수 및 배수")]),
               CropMonth(first: [Task(title: "웃거름"), Task(title: "제초, 관수 및 배수")],
                         middle: [Task(title: "제초, 관수 및 배수"), Task(title: "수확")],
                         last: [Task(title: "제초, 관수 및 배수"), Task(title: "수확")]),
               CropMonth(first: [Task(title: "수확")],
                         middle: [],
                         last: []),
               CropMonth(first: [],
                         middle: [],
                         last: [Task(title: "파종")]),
               CropMonth(first: [Task(title: "파종")],
                         middle: [Task(title: "파종"), Task(title: "웃거름")],
                         last: [Task(title: "웃거름"), Task(title: "제초, 관수 및 배수")]),
               CropMonth(first: [Task(title: "웃거름"), Task(title: "제초, 관수 및 배수")],
                         middle: [Task(title: "웃거름"), Task(title: "제초, 관수 및 배수")],
                         last: [Task(title: "웃거름"), Task(title: "제초, 관수 및 배수")]),
               CropMonth(first: [Task(title: "제초, 관수 및 배수"), Task(title: "수확")],
                         middle: [Task(title: "수확")],
                         last: [Task(title: "수확")]),
               CropMonth(first: [],
                         middle: [],
                         last: []),
               CropMonth(first: [],
                         middle: [],
                         last: []),
    ],
    problem: [CropMonth(first: [],
                        middle: [],
                        last: []),
              CropMonth(first: [],
                        middle: [],
                        last: []),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "발아불량 주의. 관수하거나 짚 또는 비닐을 덮어줍니다."), Task(title: "저온 주의", detail: "저온 감응에 의한 추대에 주의합니다. 4월 상순 이후 파종할 수 있습니다. 생육 초기에 저온 감응되지 않도록 보온 관리합니다.")],
                        middle: [Task(title: "가뭄 주의", detail: "발아불량 주의. 관수하거나 짚 또는 비닐을 덮어줍니다."), Task(title: "저온 주의", detail: "저온 감응에 의한 추대에 주의합니다. 4월 상순 이후 파종할 수 있습니다. 생육 초기에 저온 감응되지 않도록 보온 관리합니다.")],
                        last: [Task(title: "가뭄 주의", detail: "발아불량 주의. 관수하거나 짚 또는 비닐을 덮어줍니다."), Task(title: "저온 주의", detail: "저온 감응에 의한 추대에 주의합니다. 4월 상순 이후 파종할 수 있습니다. 생육 초기에 저온 감응되지 않도록 보온 관리합니다.")]),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "발아불량 주의. 관수하거나 짚 또는 비닐을 덮어줍니다."), Task(title: "저온 주의", detail: "저온 감응에 의한 추대에 주의합니다. 4월 상순 이후 파종할 수 있습니다. 생육 초기에 저온 감응되지 않도록 보온 관리합니다.")],
                        middle: [Task(title: "가뭄 주의", detail: "발아불량 주의. 관수하거나 짚 또는 비닐을 덮어줍니다."), Task(title: "저온 주의", detail: "저온 감응에 의한 추대에 주의합니다. 4월 상순 이후 파종할 수 있습니다. 생육 초기에 저온 감응되지 않도록 보온 관리합니다.")],
                        last: [Task(title: "가뭄 주의", detail: "발아불량 주의. 관수하거나 짚 또는 비닐을 덮어줍니다."), Task(title: "저온 주의", detail: "저온 감응에 의한 추대에 주의합니다. 4월 상순 이후 파종할 수 있습니다. 생육 초기에 저온 감응되지 않도록 보온 관리합니다.")]),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "발아불량 주의. 관수하거나 짚 또는 비닐을 덮어줍니다."), Task(title: "저온 주의", detail: "저온 감응에 의한 추대에 주의합니다. 4월 상순 이후 파종할 수 있습니다. 생육 초기에 저온 감응되지 않도록 보온 관리합니다.")],
                        middle: [Task(title: "잦은 비로 습해, 병해충 주의")],
                        last: [Task(title: "잦은 비로 습해, 병해충 주의")]),
              CropMonth(first: [Task(title: "잦은 비로 습해, 병해충 주의")],
                        middle: [],
                        last: []),
              CropMonth(first: [],
                        middle: [Task(title: "파종지연 주의")],
                        last: [Task(title: "파종지연 주의")]),
              CropMonth(first: [Task(title: "호우 주의", detail: "침관수 유실 및 매몰에 주의합니다. 배수구를 정비하고 엽면에 시비합니다. 살균제를 살포해 병해충을 방제합니다."), Task(title: "가뭄 주의")],
                        middle: [Task(title: "호우 주의", detail: "침관수 유실 및 매몰에 주의합니다. 배수구를 정비하고 엽면에 시비합니다. 살균제를 살포해 병해충을 방제합니다."), Task(title: "가뭄 주의")],
                        last: [Task(title: "호우 주의", detail: "침관수 유실 및 매몰에 주의합니다. 배수구를 정비하고 엽면에 시비합니다. 살균제를 살포해 병해충을 방제합니다."), Task(title: "가뭄 주의")]),
              CropMonth(first: [Task(title: "호우 주의", detail: "침관수 유실 및 매몰에 주의합니다. 배수구를 정비하고 엽면에 시비합니다. 살균제를 살포해 병해충을 방제합니다."), Task(title: "가뭄 주의")],
                        middle: [Task(title: "가뭄 주의"), Task(title: "병해충 발생 주의")],
                        last: [Task(title: "가뭄 주의"), Task(title: "병해충 발생 주의")]),
              CropMonth(first: [Task(title: "가뭄 주의"), Task(title: "병해충 발생 주의")],
                        middle: [Task(title: "가뭄 주의"), Task(title: "병해충 발생 주의")],
                        last: [Task(title: "가뭄 주의"), Task(title: "한파 주의", detail: "동해 주의. 동해 온도는 -3℃ 내외입니다. 섬피 또는 비닐을 덮습니다.")]),
              CropMonth(first: [Task(title: "가뭄 주의"), Task(title: "한파 주의", detail: "동해 주의. 동해 온도는 -3℃ 내외입니다. 섬피 또는 비닐을 덮습니다.")],
                        middle: [],
                        last: []),
              CropMonth(first: [],
                        middle: [],
                        last: []),
   ])

var grape: Crop = Crop(
    name: "포도",
    schedule: [CropMonth(first: [Task(title: "휴면기: 덕시설정비"), Task(title: "휴면기: 동계 전정")],
                         middle: [Task(title: "휴면기: 덕시설정비"), Task(title: "휴면기: 동계 전정")],
                         last: [Task(title: "휴면기: 덕시설정비"), Task(title: "휴면기: 동계 전정")]),
               CropMonth(first: [Task(title: "휴면기: 덕시설정비"), Task(title: "휴면기: 동계 전정")],
                         middle: [Task(title: "수액이동기: 눈솎기"), Task(title: "수액이동기: 병해충 방제")],
                         last: [Task(title: "수액이동기: 눈솎기"), Task(title: "수액이동기: 병해충 방제")]),
               CropMonth(first: [Task(title: "발아 및 신초생장기: 눈솎기"), Task(title: "발아 및 신초생장기: 병해충 방제")],
                         middle: [Task(title: "발아 및 신초생장기: 눈솎기"), Task(title: "발아 및 신초생장기: 병해충 방제")],
                         last: [Task(title: "발아 및 신초생장기: 순지르기"), Task(title: "발아 및 신초생장기: 꽃송이 다듬기"), Task(title: "발아 및 신초생장기: 병해충 방제")]),
               CropMonth(first: [Task(title: "발아 및 신초생장기: 순지르기"), Task(title: "발아 및 신초생장기: 꽃송이 다듬기"), Task(title: "발아 및 신초생장기: 병해충 방제")],
                         middle: [Task(title: "발아 및 신초생장기: 순지르기"), Task(title: "발아 및 신초생장기: 꽃송이 다듬기"), Task(title: "발아 및 신초생장기: 병해충 방제")],
                         last: [Task(title: "발아 및 신초생장기: 순지르기"), Task(title: "발아 및 신초생장기: 꽃송이 다듬기"), Task(title: "발아 및 신초생장기: 병해충 방제")]),
               CropMonth(first: [Task(title: "개화 및 과립비대기: 순지르기"), Task(title: "개화 및 과립비대기: 꽃송이 다듬기"), Task(title: "개화 및 과립비대기: 병해충 방제")],
                         middle: [Task(title: "개화 및 과립비대기: 송이 다듬기"), Task(title: "개화 및 과립비대기: 봉지 씌우기"), Task(title: "개화 및 과립비대기: 병해충 방제"), Task(title: "1회 웃거름")],
                         last: [Task(title: "개화 및 과립비대기: 송이 다듬기"), Task(title: "개화 및 과립비대기: 봉지 씌우기"), Task(title: "개화 및 과립비대기: 병해충 방제"), Task(title: "1회 웃거름")]),
               CropMonth(first: [Task(title: "개화 및 과립비대기: 송이 다듬기"), Task(title: "개화 및 과립비대기: 봉지 씌우기"), Task(title: "개화 및 과립비대기: 병해충 방제"), Task(title: "1회 웃거름")],
                         middle: [Task(title: "개화 및 과립비대기: 송이 다듬기"), Task(title: "개화 및 과립비대기: 봉지 씌우기"), Task(title: "개화 및 과립비대기: 병해충 방제"), Task(title: "1회 웃거름")],
                         last: [Task(title: "개화 및 과립비대기: 송이 다듬기"), Task(title: "개화 및 과립비대기: 봉지 씌우기"), Task(title: "개화 및 과립비대기: 병해충 방제"), Task(title: "1회 웃거름")]),
               CropMonth(first: [Task(title: "개화 및 과립비대기: 송이 다듬기"), Task(title: "개화 및 과립비대기: 봉지 씌우기"), Task(title: "개화 및 과립비대기: 병해충 방제"), Task(title: "1회 웃거름")],
                         middle: [Task(title: "개화 및 과립비대기: 신초관리"), Task(title: "개화 및 과립비대기: 생리장해 대책"), Task(title: "개화 및 과립비대기: 병해충 방제")],
                         last: [Task(title: "성숙기: 신초관리"), Task(title: "성숙기: 생리장해 대책"), Task(title: "성숙기: 병해충 방제")]),
               CropMonth(first: [Task(title: "성숙기: 신초관리"), Task(title: "성숙기: 생리장해 대책"), Task(title: "성숙기: 병해충 방제")],
                         middle: [Task(title: "성숙기: 신초관리"), Task(title: "성숙기: 생리장해 대책"), Task(title: "성숙기: 병해충 방제")],
                         last: [Task(title: "성숙기: 신초관리"), Task(title: "성숙기: 생리장해 대책"), Task(title: "성숙기: 병해충 방제")]),
               CropMonth(first: [Task(title: "수확 및 저장양분 축적기: 조, 중생종 수확"), Task(title: "수확 및 저장양분 축적기: 병해충 방제")],
                         middle: [Task(title: "수확 및 저장양분 축적기: 조, 중생종 수확"), Task(title: "수확 및 저장양분 축적기: 병해충 방제")],
                         last: [Task(title: "수확 및 저장양분 축적기: 조, 중생종 수확"), Task(title: "수확 및 저장양분 축적기: 병해충 방제")]),
               CropMonth(first: [Task(title: "수확 및 저장양분 축적기: 조, 중생종 수확"), Task(title: "수확 및 저장양분 축적기: 병해충 방제")],
                         middle: [Task(title: "수확 및 저장양분 축적기: 만생종 수확"), Task(title: "수확 및 저장양분 축적기: 병해충 방제"), Task(title: "수확 및 저장양분 축적기: 2회 웃거름") ],
                         last: [Task(title: "수확 및 저장양분 축적기: 만생종 수확"), Task(title: "수확 및 저장양분 축적기: 병해충 방제"), Task(title: "수확 및 저장양분 축적기: 2회 웃거름") ]),
               CropMonth(first: [Task(title: "수확 및 저장양분 축적기: 만생종 수확"), Task(title: "수확 및 저장양분 축적기: 병해충 방제"), Task(title: "수확 및 저장양분 축적기: 2회 웃거름") ],
                         middle: [Task(title: "낙엽기: 낙엽시비")],
                         last: [Task(title: "낙엽기: 낙엽시비")]),
               CropMonth(first: [Task(title: "낙엽기: 낙엽시비")],
                         middle: [Task(title: "휴면기: 낙엽시비")],
                         last: [Task(title: "휴면기: 낙엽시비")]),
    ],
    problem: [CropMonth(first: [Task(title: "혹한 및 건조 주의", detail: "휴면병, 발아불량 주의. 조기낙엽과 과다착과를 방지합니다. 월동 전에 저장양분을 충분히 축적하게 하세요. 월동 전에 충분히 관수하세요.")],
                        middle: [Task(title: "혹한 및 건조 주의", detail: "휴면병, 발아불량 주의. 조기낙엽과 과다착과를 방지합니다. 월동 전에 저장양분을 충분히 축적하게 하세요. 월동 전에 충분히 관수하세요.")],
                        last: [Task(title: "혹한 및 건조 주의", detail: "휴면병, 발아불량 주의. 조기낙엽과 과다착과를 방지합니다. 월동 전에 저장양분을 충분히 축적하게 하세요. 월동 전에 충분히 관수하세요.")]),
              CropMonth(first: [Task(title: "혹한 및 건조 주의", detail: "휴면병, 발아불량 주의. 조기낙엽과 과다착과를 방지합니다. 월동 전에 저장양분을 충분히 축적하게 하세요. 월동 전에 충분히 관수하세요.")],
                        middle: [Task(title: "혹한 및 건조 주의", detail: "휴면병, 발아불량 주의. 조기낙엽과 과다착과를 방지합니다. 월동 전에 저장양분을 충분히 축적하게 하세요. 월동 전에 충분히 관수하세요.")],
                        last: [Task(title: "가뭄 주의", detail: "휴면병, 발아불량 주의. 미니스프링쿨러 및 점적관수를 설치해 관수합니다. 5월 중순에 비가림 비닐을 피복합니다. ")]),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "휴면병, 발아불량 주의. 미니스프링쿨러 및 점적관수를 설치해 관수합니다. 5월 중순에 비가림 비닐을 피복합니다. ")],
                        middle: [Task(title: "가뭄 주의", detail: "발아불량, 초기생육 불균일 주의. 미니스프링쿨러 및 점적관수를 설치해 관수합니다. 5월 중순에 비가림 비닐을 피복합니다. ")],
                        last: [Task(title: "가뭄 주의", detail: "발아불량, 초기생육 불균일 주의. 미니스프링쿨러 및 점적관수를 설치해 관수합니다. 5월 중순에 비가림 비닐을 피복합니다. ")]),
              CropMonth(first: [Task(title: "가뭄 주의", detail: "발아불량, 초기생육 불균일 주의. 미니스프링쿨러 및 점적관수를 설치해 관수합니다. 5월 중순에 비가림 비닐을 피복합니다. ")],
                        middle: [Task(title: "가뭄 주의", detail: "발아불량, 초기생육 불균일 주의. 미니스프링쿨러 및 점적관수를 설치해 관수합니다. 5월 중순에 비가림 비닐을 피복합니다. ")],
                        last: [Task(title: "가뭄 주의", detail: "발아불량, 초기생육 불균일 주의. 미니스프링쿨러 및 점적관수를 설치해 관수합니다. 5월 중순에 비가림 비닐을 피복합니다. ")]),
              CropMonth(first: [Task(title: "생육기 저온 및 기상불량 주의", detail: "발아불량, 초기생육 불균일 주의. 미니스프링쿨러 및 점적관수를 설치해 관수합니다. 5월 중순에 비가림 비닐을 피복합니다. ")],
                        middle: [Task(title: "생육기 저온 및 기상불량 주의", detail: "신초고사, 꽃떨이 현상 주의. 적정 주간거리를 확보합니다. 대립계 포도는 하향유인해 전정하고, 착립증진제를 살포합니다.")],
                        last: [Task(title: "생육기 저온 및 기상불량 주의", detail: "신초고사, 꽃떨이 현상 주의. 적정 주간거리를 확보합니다. 대립계 포도는 하향유인해 전정하고, 착립증진제를 살포합니다.")]),
              CropMonth(first: [Task(title: "생육기 저온 및 기상불량 주의", detail: "신초고사, 꽃떨이 현상 주의. 적정 주간거리를 확보합니다. 대립계 포도는 하향유인해 전정하고, 착립증진제를 살포합니다.")],
                        middle: [Task(title: "생육기 저온 및 기상불량 주의", detail: "신초고사, 꽃떨이 현상 주의. 적정 주간거리를 확보합니다. 대립계 포도는 하향유인해 전정하고, 착립증진제를 살포합니다.")],
                        last: [Task(title: "생육기 저온 및 기상불량 주의", detail: "신초고사, 꽃떨이 현상 주의. 적정 주간거리를 확보합니다. 대립계 포도는 하향유인해 전정하고, 착립증진제를 살포합니다.")]),
              CropMonth(first: [Task(title: "생육기 저온 및 기상불량 주의", detail: "신초고사, 꽃떨이 현상 주의. 적정 주간거리를 확보합니다. 대립계 포도는 하향유인해 전정하고, 착립증진제를 살포합니다.")],
                        middle: [Task(title: "호우 및 태풍 주의", detail: "열과, 조기낙엽 덕시설 도복에 주의합니다. 수세 안정에 신경쓰세요. 성숙기 신초생장정지율은 80%입니다. 폭 180~300cm, 높이 40~50cm의 이랑 재배하세요. 송이를 다듬고 적정 착과량 확보에 유의하세요.")],
                        last: [Task(title: "호우 및 태풍 주의", detail: "열과, 조기낙엽 덕시설 도복에 주의합니다. 수세 안정에 신경쓰세요. 성숙기 신초생장정지율은 80%입니다. 폭 180~300cm, 높이 40~50cm의 이랑 재배하세요. 송이를 다듬고 적정 착과량 확보에 유의하세요.")]),
              CropMonth(first: [Task(title: "호우 및 태풍 주의", detail: "열과, 조기낙엽 덕시설 도복에 주의합니다. 수세 안정에 신경쓰세요. 성숙기 신초생장정지율은 80%입니다. 폭 180~300cm, 높이 40~50cm의 이랑 재배하세요. 송이를 다듬고 적정 착과량 확보에 유의하세요.")],
                        middle: [Task(title: "호우 및 태풍 주의", detail: "열과, 조기낙엽 덕시설 도복에 주의합니다. 수세 안정에 신경쓰세요. 성숙기 신초생장정지율은 80%입니다. 폭 180~300cm, 높이 40~50cm의 이랑 재배하세요. 송이를 다듬고 적정 착과량 확보에 유의하세요.")],
                        last: [Task(title: "호우 및 태풍 주의", detail: "열과, 조기낙엽 덕시설 도복에 주의합니다. 수세 안정에 신경쓰세요. 성숙기 신초생장정지율은 80%입니다. 폭 180~300cm, 높이 40~50cm의 이랑 재배하세요. 송이를 다듬고 적정 착과량 확보에 유의하세요.")]),
              CropMonth(first: [Task(title: "호우 및 태풍 주의", detail: "열과, 조기낙엽 덕시설 도복에 주의합니다. 수세 안정에 신경쓰세요. 성숙기 신초생장정지율은 80%입니다. 폭 180~300cm, 높이 40~50cm의 이랑 재배하세요. 송이를 다듬고 적정 착과량 확보에 유의하세요.")],
                        middle: [Task(title: "호우 및 태풍 주의", detail: "열과, 조기낙엽 덕시설 도복에 주의합니다. 수세 안정에 신경쓰세요. 성숙기 신초생장정지율은 80%입니다. 폭 180~300cm, 높이 40~50cm의 이랑 재배하세요. 송이를 다듬고 적정 착과량 확보에 유의하세요.")],
                        last: [Task(title: "호우 및 태풍 주의", detail: "열과, 조기낙엽 덕시설 도복에 주의합니다. 수세 안정에 신경쓰세요. 성숙기 신초생장정지율은 80%입니다. 폭 180~300cm, 높이 40~50cm의 이랑 재배하세요. 송이를 다듬고 적정 착과량 확보에 유의하세요.")]),
              CropMonth(first: [Task(title: "호우 및 태풍 주의", detail: "열과, 조기낙엽 덕시설 도복에 주의합니다. 수세 안정에 신경쓰세요. 성숙기 신초생장정지율은 80%입니다. 폭 180~300cm, 높이 40~50cm의 이랑 재배하세요. 송이를 다듬고 적정 착과량 확보에 유의하세요.")],
                        middle: [Task(title: "호우 및 태풍 주의", detail: "열과, 조기낙엽 덕시설 도복에 주의합니다. 수세 안정에 신경쓰세요. 성숙기 신초생장정지율은 80%입니다. 폭 180~300cm, 높이 40~50cm의 이랑 재배하세요. 송이를 다듬고 적정 착과량 확보에 유의하세요.")],
                        last: [Task(title: "호우 및 태풍 주의", detail: "열과, 조기낙엽 덕시설 도복에 주의합니다. 수세 안정에 신경쓰세요. 성숙기 신초생장정지율은 80%입니다. 폭 180~300cm, 높이 40~50cm의 이랑 재배하세요. 송이를 다듬고 적정 착과량 확보에 유의하세요.")]),
              CropMonth(first: [Task(title: "호우 및 태풍 주의", detail: "열과, 조기낙엽 덕시설 도복에 주의합니다. 수세 안정에 신경쓰세요. 성숙기 신초생장정지율은 80%입니다. 폭 180~300cm, 높이 40~50cm의 이랑 재배하세요. 송이를 다듬고 적정 착과량 확보에 유의하세요.")],
                        middle: [Task(title: "혹한 및 건조 주의", detail: "휴면병, 발아불량 주의. 조기낙엽과 과다착과를 방지하세요. 월동 전에 저장양분을 충분히 축적하게 하세요. 월동 전에 충분히 관수하세요.")],
                        last: [Task(title: "혹한 및 건조 주의", detail: "휴면병, 발아불량 주의. 조기낙엽과 과다착과를 방지하세요. 월동 전에 저장양분을 충분히 축적하게 하세요. 월동 전에 충분히 관수하세요.")]),
              CropMonth(first: [Task(title: "혹한 및 건조 주의", detail: "휴면병, 발아불량 주의. 조기낙엽과 과다착과를 방지하세요. 월동 전에 저장양분을 충분히 축적하게 하세요. 월동 전에 충분히 관수하세요.")],
                        middle: [Task(title: "혹한 및 건조 주의", detail: "휴면병, 발아불량 주의. 조기낙엽과 과다착과를 방지하세요. 월동 전에 저장양분을 충분히 축적하게 하세요. 월동 전에 충분히 관수하세요.")],
                        last: [Task(title: "혹한 및 건조 주의", detail: "휴면병, 발아불량 주의. 조기낙엽과 과다착과를 방지하세요. 월동 전에 저장양분을 충분히 축적하게 하세요. 월동 전에 충분히 관수하세요.")]),
   ])

var eggplant: Crop = Crop(
    name: "가지",
    schedule: [CropMonth(first: [Task(title: "수확"), Task(title: "주지적심"), Task(title: "측지"), Task(title: "병해충 예찰 및 예방적 방제")],
                         middle: [Task(title: "수확"), Task(title: "주지적심"), Task(title: "측지"), Task(title: "병해충 예찰 및 예방적 방제")],
                         last: [Task(title: "수확"), Task(title: "주지적심"), Task(title: "측지"), Task(title: "병해충 예찰 및 예방적 방제")]),
               CropMonth(first: [Task(title: "수확"), Task(title: "측지 정지"), Task(title: "병해충 예찰 및 예방적 방제")],
                         middle: [Task(title: "수확"), Task(title: "측지 정지"), Task(title: "병해충 예찰 및 예방적 방제")],
                         last: [Task(title: "수확"), Task(title: "측지 정지"), Task(title: "병해충 예찰 및 예방적 방제")]),
               CropMonth(first: [Task(title: "수확"), Task(title: "측지 정지"), Task(title: "병해충 예찰 및 예방적 방제")],
                         middle: [Task(title: "수확"), Task(title: "측지 정지"), Task(title: "병해충 예찰 및 예방적 방제")],
                         last: [Task(title: "수확"), Task(title: "측지 정지"), Task(title: "병해충 예찰 및 예방적 방제")]),
               CropMonth(first: [Task(title: "수확"), Task(title: "측지 정지"), Task(title: "병해충 예찰 및 예방적 방제")],
                         middle: [Task(title: "수확"), Task(title: "측지 정지"), Task(title: "병해충 예찰 및 예방적 방제")],
                         last: [Task(title: "수확"), Task(title: "가온 완료"), Task(title: "병해충 예찰 및 예방적 방제")]),
               CropMonth(first: [Task(title: "수확"), Task(title: "가온 완료"), Task(title: "병해충 예찰 및 예방적 방제")],
                         middle: [Task(title: "수확"), Task(title: "병해충 예찰 및 예방적 방제")],
                         last: [Task(title: "수확"), Task(title: "병해충 예찰 및 예방적 방제")]),
               CropMonth(first: [Task(title: "수확"), Task(title: "병해충 예찰 및 예방적 방제")],
                         middle: [Task(title: "파종"), Task(title: "병해충 예찰 및 예방적 방제")],
                         last: [Task(title: "파종"), Task(title: "병해충 예찰 및 예방적 방제")]),
               CropMonth(first: [Task(title: "토양 소독", detail: "태양열과 열수 등 물리적 소독, 다조메입제 등 화학적 소독 등이 있습니다.")],
                         middle: [Task(title: "토양 소독", detail: "태양열과 열수 등 물리적 소독, 다조메입제 등 화학적 소독 등이 있습니다."), Task(title: "접목")],
                         last: [Task(title: "토양 소독", detail: "태양열과 열수 등 물리적 소독, 다조메입제 등 화학적 소독 등이 있습니다."), Task(title: "접목")]),
               CropMonth(first: [Task(title: "활착"), Task(title: "정식 준비")],
                         middle: [Task(title: "활착"), Task(title: "정식 준비")],
                         last: [Task(title: "정식"), Task(title: "유인, 착과제 처리 ", detail: "유인은 Y자형 4주지가 기본입니다. 첫번째 꽃 아래의 건실한 측지를 2번째 주지로, 두번째 꽃 아래 건실한 측지를 3번째 주지, 3번째 꽃 아래 건실한 측지를 4번째 주지로 유인합니다.")]),
               CropMonth(first: [Task(title: "정식"), Task(title: "유인, 착과제 처리 ", detail: "유인은 Y자형 4주지가 기본입니다. 첫번째 꽃 아래의 건실한 측지를 2번째 주지로, 두번째 꽃 아래 건실한 측지를 3번째 주지, 3번째 꽃 아래 건실한 측지를 4번째 주지로 유인합니다."), Task(title: "온실피복교체", detail: "전년도에 사용한 피복은 광투과량이 떨어지므로 매년 교체합니다.")],
                         middle: [Task(title: "착과"), Task(title: "유인, 착과제 처리 ", detail: "유인은 Y자형 4주지가 기본입니다. 첫번째 꽃 아래의 건실한 측지를 2번째 주지로, 두번째 꽃 아래 건실한 측지를 3번째 주지, 3번째 꽃 아래 건실한 측지를 4번째 주지로 유인합니다."), Task(title: "온실피복교체", detail: "전년도에 사용한 피복은 광투과량이 떨어지므로 매년 교체합니다.")],
                         last: [Task(title: "착과"), Task(title: "유인, 착과제 처리 ", detail: "유인은 Y자형 4주지가 기본입니다. 첫번째 꽃 아래의 건실한 측지를 2번째 주지로, 두번째 꽃 아래 건실한 측지를 3번째 주지, 3번째 꽃 아래 건실한 측지를 4번째 주지로 유인합니다."), Task(title: "온실피복교체", detail: "전년도에 사용한 피복은 광투과량이 떨어지므로 매년 교체합니다.")]),
               CropMonth(first: [Task(title: "착과"), Task(title: "멀칭", detail: "고온기는 피하고 9월 중순 이후 지온이 낮은 시기에 멀칭합니다."), Task(title: "온실피복교체")],
                         middle: [Task(title: "수확"), Task(title: "멀칭", detail: "고온기는 피하고 9월 중순 이후 지온이 낮은 시기에 멀칭합니다.")],
                         last: [Task(title: "수확"), Task(title: "가온"), Task(title: "추비")]),
               CropMonth(first: [Task(title: "수확"), Task(title: "가온"), Task(title: "추비")],
                         middle: [Task(title: "수확"), Task(title: "노화엽 적엽"), Task(title: "병해충 예찰 및 예방적 방제")],
                         last: [Task(title: "수확"), Task(title: "노화엽 적엽"), Task(title: "병해충 예찰 및 예방적 방제")]),
               CropMonth(first: [Task(title: "수확"), Task(title: "노화엽 적엽"), Task(title: "병해충 예찰 및 예방적 방제")],
                         middle: [Task(title: "수확"), Task(title: "주지적심"), Task(title: "측지"), Task(title: "병해충 예찰 및 예방적 방제")],
                         last: [Task(title: "수확"), Task(title: "주지적심"), Task(title: "측지"), Task(title: "병해충 예찰 및 예방적 방제")]),
    ],
    problem: [CropMonth(first: [Task(title: "생장조정제(착과제)로 인한 장해 주의"), Task(title: "곡과 주의", detail: "곡과는 일조부족, 양분부족, 과다착과, 식물체 세력 약화, 지베렐린 첨가에 의한 과일에서의 양분 불균형으로 발생합니다."), Task(title: "돌가지 주의", detail: "돌가지는 저온기 광합성량 부족, 일조부족, 과번무, 단화주화 등에 의한 과일로의 광합성 양분의 전류 부족에 의해 발생합니다. ")],
                        middle: [Task(title: "생장조정제(착과제)로 인한 장해 주의"), Task(title: "곡과 주의", detail: "곡과는 일조부족, 양분부족, 과다착과, 식물체 세력 약화, 지베렐린 첨가에 의한 과일에서의 양분 불균형으로 발생합니다."), Task(title: "돌가지 주의", detail: "돌가지는 저온기 광합성량 부족, 일조부족, 과번무, 단화주화 등에 의한 과일로의 광합성 양분의 전류 부족에 의해 발생합니다. "), Task(title: "잿빛곰팡이 주의", detail: "저온다습 조건에서 많이 발병합니다. 방제가 어려우므로, 환경적으로 예방해야 합니다. 발병 초기에 이 병 부위는 제거하고 온실 밖으로 방출합니다.")],
                        last: [Task(title: "생장조정제(착과제)로 인한 장해 주의"), Task(title: "곡과 주의", detail: "곡과는 일조부족, 양분부족, 과다착과, 식물체 세력 약화, 지베렐린 첨가에 의한 과일에서의 양분 불균형으로 발생합니다."), Task(title: "돌가지 주의", detail: "돌가지는 저온기 광합성량 부족, 일조부족, 과번무, 단화주화 등에 의한 과일로의 광합성 양분의 전류 부족에 의해 발생합니다. "), Task(title: "잿빛곰팡이 주의", detail: "저온다습 조건에서 많이 발병합니다. 방제가 어려우므로, 환경적으로 예방해야 합니다. 발병 초기에 이 병 부위는 제거하고 온실 밖으로 방출합니다.")]),
              CropMonth(first: [Task(title: "생장조정제(착과제)로 인한 장해 주의"), Task(title: "곡과 주의", detail: "곡과는 일조부족, 양분부족, 과다착과, 식물체 세력 약화, 지베렐린 첨가에 의한 과일에서의 양분 불균형으로 발생합니다."), Task(title: "돌가지 주의", detail: "돌가지는 저온기 광합성량 부족, 일조부족, 과번무, 단화주화 등에 의한 과일로의 광합성 양분의 전류 부족에 의해 발생합니다. "), Task(title: "잿빛곰팡이 주의", detail: "저온다습 조건에서 많이 발병합니다. 방제가 어려우므로, 환경적으로 예방해야 합니다. 발병 초기에 이 병 부위는 제거하고 온실 밖으로 방출합니다.")],
                        middle: [Task(title: "생장조정제(착과제)로 인한 장해 주의"), Task(title: "곡과 주의", detail: "곡과는 일조부족, 양분부족, 과다착과, 식물체 세력 약화, 지베렐린 첨가에 의한 과일에서의 양분 불균형으로 발생합니다."), Task(title: "돌가지 주의", detail: "돌가지는 저온기 광합성량 부족, 일조부족, 과번무, 단화주화 등에 의한 과일로의 광합성 양분의 전류 부족에 의해 발생합니다. "), Task(title: "잿빛곰팡이 주의", detail: "저온다습 조건에서 많이 발병합니다. 방제가 어려우므로, 환경적으로 예방해야 합니다. 발병 초기에 이 병 부위는 제거하고 온실 밖으로 방출합니다.")],
                        last: [Task(title: "잎 마그네슘 결핍", detail: "저온기에 일조가 부족하거나, 과다 착과 등에 의해 뿌리 발육이 저하될 때 발생합니다."), Task(title: "잿빛곰팡이 주의", detail: "저온다습 조건에서 많이 발병합니다. 방제가 어려우므로, 환경적으로 예방해야 합니다. 발병 초기에 이 병 부위는 제거하고 온실 밖으로 방출합니다.")]),
              CropMonth(first: [Task(title: "잎 마그네슘 결핍 주의", detail: "저온기에 일조가 부족하거나, 과다 착과 등에 의해 뿌리 발육이 저하될 때 발생합니다.")],
                        middle: [Task(title: "잎 마그네슘 결핍 주의", detail: "저온기에 일조가 부족하거나, 과다 착과 등에 의해 뿌리 발육이 저하될 때 발생합니다.")],
                        last: [Task(title: "일소과 주의", detail: "3월 이후 온도가 상승하는 시기 또는 비 온 다음 날 많이 발생합니다. 토양의 수분이 부족하거나, 오전에 환기 시 급격한 온도 변화에 의해 발생할 확률이 높아지므로 주의합니다.")]),
              CropMonth(first: [Task(title: "일소과 주의", detail: "3월 이후 온도가 상승하는 시기 또는 비 온 다음 날 많이 발생합니다. 토양의 수분이 부족하거나, 오전에 환기 시 급격한 온도 변화에 의해 발생할 확률이 높아지므로 주의합니다.")],
                        middle: [Task(title: "일소과 주의", detail: "3월 이후 온도가 상승하는 시기 또는 비 온 다음 날 많이 발생합니다. 토양의 수분이 부족하거나, 오전에 환기 시 급격한 온도 변화에 의해 발생할 확률이 높아지므로 주의합니다.")],
                        last: [Task(title: "일소과 주의", detail: "3월 이후 온도가 상승하는 시기 또는 비 온 다음 날 많이 발생합니다. 토양의 수분이 부족하거나, 오전에 환기 시 급격한 온도 변화에 의해 발생할 확률이 높아지므로 주의합니다.")]),
              CropMonth(first: [Task(title: "비광택과 주의", detail: "고온기에 건조 또는 온실 내 고온에 의한 수분 부족으로 발생합니다.")],
                        middle: [Task(title: "비광택과 주의", detail: "고온기에 건조 또는 온실 내 고온에 의한 수분 부족으로 발생합니다.")],
                        last: [Task(title: "비광택과 주의", detail: "고온기에 건조 또는 온실 내 고온에 의한 수분 부족으로 발생합니다.")]),
              CropMonth(first: [Task(title: "비광택과 주의", detail: "고온기에 건조 또는 온실 내 고온에 의한 수분 부족으로 발생합니다.")],
                        middle: [Task(title: "비광택과 주의", detail: "고온기에 건조 또는 온실 내 고온에 의한 수분 부족으로 발생합니다.")],
                        last: [Task(title: "비광택과 주의", detail: "고온기에 건조 또는 온실 내 고온에 의한 수분 부족으로 발생합니다.")]),
              CropMonth(first: [],
                        middle: [],
                        last: []),
              CropMonth(first: [],
                        middle: [Task(title: "습해 주의")],
                        last: [Task(title: "습해 주의")]),
              CropMonth(first: [],
                        middle: [],
                        last: []),
              CropMonth(first: [],
                        middle: [],
                        last: [Task(title: "저온장해 주의")]),
              CropMonth(first: [Task(title: "저온장해 주의")],
                        middle: [Task(title: "저온장해 주의")],
                        last: [Task(title: "저온장해 주의")]),
              CropMonth(first: [Task(title: "생장조정제(착과제)로 인한 장해 주의"), Task(title: "곡과 주의", detail: "곡과는 일조부족, 양분부족, 과다착과, 식물체 세력 약화, 지베렐린 첨가에 의한 과일에서의 양분 불균형으로 발생합니다."), Task(title: "돌가지 주의", detail: "돌가지는 저온기 광합성량 부족, 일조부족, 과번무, 단화주화 등에 의한 과일로의 광합성 양분의 전류 부족에 의해 발생합니다. ")],
                        middle: [Task(title: "생장조정제(착과제)로 인한 장해 주의"), Task(title: "곡과 주의", detail: "곡과는 일조부족, 양분부족, 과다착과, 식물체 세력 약화, 지베렐린 첨가에 의한 과일에서의 양분 불균형으로 발생합니다."), Task(title: "돌가지 주의", detail: "돌가지는 저온기 광합성량 부족, 일조부족, 과번무, 단화주화 등에 의한 과일로의 광합성 양분의 전류 부족에 의해 발생합니다. ")],
                        last: [Task(title: "생장조정제(착과제)로 인한 장해 주의"), Task(title: "곡과 주의", detail: "곡과는 일조부족, 양분부족, 과다착과, 식물체 세력 약화, 지베렐린 첨가에 의한 과일에서의 양분 불균형으로 발생합니다."), Task(title: "돌가지 주의", detail: "돌가지는 저온기 광합성량 부족, 일조부족, 과번무, 단화주화 등에 의한 과일로의 광합성 양분의 전류 부족에 의해 발생합니다. ")]),
   ])

//var cropnamename: Crop = Crop(
//    name: "",
//    schedule: [CropMonth(first: <#T##[Task]#>,
//                         middle: <#T##[Task]#>,
//                         last: <#T##[Task]#>),
//               CropMonth(first: <#T##[Task]#>,
//                         middle: <#T##[Task]#>,
//                         last: <#T##[Task]#>),
//               CropMonth(first: <#T##[Task]#>,
//                         middle: <#T##[Task]#>,
//                         last: <#T##[Task]#>),
//               CropMonth(first: <#T##[Task]#>,
//                         middle: <#T##[Task]#>,
//                         last: <#T##[Task]#>),
//               CropMonth(first: <#T##[Task]#>,
//                         middle: <#T##[Task]#>,
//                         last: <#T##[Task]#>),
//               CropMonth(first: <#T##[Task]#>,
//                         middle: <#T##[Task]#>,
//                         last: <#T##[Task]#>),
//               CropMonth(first: <#T##[Task]#>,
//                         middle: <#T##[Task]#>,
//                         last: <#T##[Task]#>),
//               CropMonth(first: <#T##[Task]#>,
//                         middle: <#T##[Task]#>,
//                         last: <#T##[Task]#>),
//               CropMonth(first: <#T##[Task]#>,
//                         middle: <#T##[Task]#>,
//                         last: <#T##[Task]#>),
//               CropMonth(first: <#T##[Task]#>,
//                         middle: <#T##[Task]#>,
//                         last: <#T##[Task]#>),
//               CropMonth(first: <#T##[Task]#>,
//                         middle: <#T##[Task]#>,
//                         last: <#T##[Task]#>),
//               CropMonth(first: <#T##[Task]#>,
//                         middle: <#T##[Task]#>,
//                         last: <#T##[Task]#>),
//    ],
//    problem: [CropMonth(first: <#T##[Task]#>,
//                        middle: <#T##[Task]#>,
//                        last: <#T##[Task]#>),
//              CropMonth(first: <#T##[Task]#>,
//                        middle: <#T##[Task]#>,
//                        last: <#T##[Task]#>),
//              CropMonth(first: <#T##[Task]#>,
//                        middle: <#T##[Task]#>,
//                        last: <#T##[Task]#>),
//              CropMonth(first: <#T##[Task]#>,
//                        middle: <#T##[Task]#>,
//                        last: <#T##[Task]#>),
//              CropMonth(first: <#T##[Task]#>,
//                        middle: <#T##[Task]#>,
//                        last: <#T##[Task]#>),
//              CropMonth(first: <#T##[Task]#>,
//                        middle: <#T##[Task]#>,
//                        last: <#T##[Task]#>),
//              CropMonth(first: <#T##[Task]#>,
//                        middle: <#T##[Task]#>,
//                        last: <#T##[Task]#>),
//              CropMonth(first: <#T##[Task]#>,
//                        middle: <#T##[Task]#>,
//                        last: <#T##[Task]#>),
//              CropMonth(first: <#T##[Task]#>,
//                        middle: <#T##[Task]#>,
//                        last: <#T##[Task]#>),
//              CropMonth(first: <#T##[Task]#>,
//                        middle: <#T##[Task]#>,
//                        last: <#T##[Task]#>),
//              CropMonth(first: <#T##[Task]#>,
//                        middle: <#T##[Task]#>,
//                        last: <#T##[Task]#>),
//              CropMonth(first: <#T##[Task]#>,
//                        middle: <#T##[Task]#>,
//                        last: <#T##[Task]#>),
//   ])
